### ISSUE TITLE
Edge-php-sdk 1.1.21 generated a pending status problem for new app/key.

### ISSUE THREAD

**Issue by kruczi** [apigee/edge-php-sdk#114]
After update from edge-php-sdk 1.1.20 to edge-php-sdk 1.1.21 we discovered a problem with the status for new app/key created on the portal.
The SDK in versions older than 1.1.21 allowed to create apps/key with the possibility of their immediate use. They received the status of approved 
(at least in our Dev Portal implementation, DeveloperApp status was not sent to Edge).

After the change from fa6592a4642dc20672b1560780a31ec576c67ad4, the status for new app/key was set to `pending`.

from AbstractApp.php
```
/**
 * Restores this object to its pristine state.
 */
public function blankValues()
{
...
    $this->name = null;
    $this->scopes = array();
    $this->status = 'pending';
    $this->description = null;
...
}
```
The method `blankValues` is used in the constructor of class `DeveloperApp`.

I wonder if only we have that problem with *pending* status because probably there can be a situation where other developers also could have that same result after using the new version of `edge-php-sdk`.

**Comment by cnovak** [comment]
I tested this and see another issue:  I get the error `No status found in cps for status:edge-app-status` with CPS orgs.  I will put out a new version to fix this issue.

**Comment by cnovak** [comment]
@kruczi thanks for submitting this issue.  Version 1.1.22 is now released https://github.com/apigee/edge-php-sdk/releases/tag/1.1.22 with this fix.
