### ISSUE TITLE
2.0 release date?

### ISSUE THREAD

**Issue by dingo-d** [apigee/edge-php-sdk#95]
I'm wondering if there is any release date for the 2.0 version? And if I implement 1.x version will it be hard to migrate to 2.x version later on when it becomes stable?

**Comment by cnovak** [comment]
@dingo-d we are still working through everything for the 2.0 version, but plan to release a solid version around April-June. I know that is not a specific deadline but there are some unknowns in the project.

The 2.x is a complete rewrite, so if you use 1.x,  you will have to modify everything to move to 2.0.  I am not sure what your timelines are, but I would recommend using 2.0 if possible.  We are writing this in an iterative way, so if the parts of the API are already implemented, you could try using it now.  The design patterns and architecture are set up at this point so there should not be a lot of changes in the base code.

**Comment by dingo-d** [comment]
Thanks for the answer it helps a lot :)

**Comment by cnovak** [comment]
@dingo-d wanted to let you know that we moved the new version of this library to the repo [https://github.com/apigee/apigee-client-php](https://github.com/apigee/apigee-client-php).  Please feel free to submit issues in that repo if you come across any issues w/the alpha release.

**Comment by dingo-d** [comment]
Thanks!
